---
  - name: VMware VM Inventory Generator
    hosts: localhost
    gather_facts: no
    tasks:   
      - name: collect VMs in specific folder
        vmware_vm_facts:
             validate_certs: False
             hostname: "{{ vcenter_hostname }}"
             username: "{{ vcenter_username }}"
             password: "{{ vcenter_passwd }}"
        #     folder: "{{ vcenter_folder }}"
        delegate_to: localhost
        register: vm_info
     
      - name: print VM info
        debug:
           msg: "{{ item['guest_name'] }}"
        with_items: "{{ vm_info.virtual_machines }}"
    #    when: "{{ vm_info.virtual_machines.power_state }}"=="{{ poweredOff }}"
     
      - name: Show virtual machines guest_name in job log
        ansible.builtin.debug:
          msg: "{{ item['guest_name'] }}"
        with_items: "{{ vm_info.virtual_machines }}"
      - name: Print virtual machines guest_name in output file
        ansible.builtin.copy: # should really use template here
          content: |
              Virtual Machine Names
              {% for vm in vm_info.virtual_machines %}
              {{ vm['guest_name'] }}
              {% endfor %}
          dest: /etc/ansible/reports/virtual_machine_names.txt
          
      - name: Gather facts for vm summary
        vmware_guest_facts:
          hostname: "{{ hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          validate_certs: no
          datacenter: DC
          name: "{{ item }}"
        delegate_to: localhost  
        with_lines: /etc/ansible/reports/virtual_machine_names.txt 
        register: gather_facts_for_vm_summary_result
    #    loop: "{{ vms.virtual_machines }}"
     #   loop_control:
      #    label: "{{ item.guest_name }}"
