---
- name: Enable SSH on ESXi Hosts
  hosts: localhost
  connection: local
  vars_files:
    - vars2.yml
	
  tasks:
    - name: Connect to vCenter servers and retrieve ESXi host information
      vmware_host:
        hostname: "{{ item }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        gather_vm_hosts: yes
        gather_nic_info: yes
        gather_vswitch_info: yes
      register: vmware_info
      with_items: "{{ vcenter_servers }}"
