---
- name: VMware VM Inventory Generator
  hosts: localhost
  gather_facts: no
 # vars:

  tasks:
    - name: Gather fact for all vm
      vmware_vm_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: vms
      
    - name: Gather snapshot information about the virtual machine using MoID
      vmware_guest_snapshot_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: DC
        folder: /DC/vm/
        name: ESXi6.7
       # name: "{{ item.guest_name }}"
        validate_certs: no
      register: snapshot_info
     # loop: "{{ vms.virtual_machines }}"
     # loop_control:
      #  label: "{{ item.guest_name }}"
        #name: ESX6.7-1
        #validate_certs: no
      #delegate_to: localhost
      #register: snapshot_info
    - name: debug snapshotinfo  
      debug: var=snapshot_info.results.guest_snapshots.current_snapshot
      
      
