---
- name: VMware VM Inventory Generator
  hosts: localhost
  gather_facts: no
 # vars:

  tasks:
    - name: Gather fact for all vm
      vmware_vm_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: vms
      
    - name: Gather snapshot information about the virtual machine using MoID
      community.vmware.vmware_guest_snapshot_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: DC
        name: ESX6.7-1
      delegate_to: localhost
      register: snapshot_info
      debug:
        msg: vms.virtual_machines
      
      
