---
- name: VMware VM Inventory Generator
  hosts: localhost
  gather_facts: no
 # vars:

  tasks:
    - name: Gather snapshot information about the virtual machine in the given vCenter
      vmware_guest_snapshot_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: DC
        folder: /DC/vm/
      register: gather_facts_for_vm_summary_result
