---
  - name: VMware VM Inventory Generator
    hosts: localhost
    gather_facts: no
task:       
  - name: Display all cluster names
    ansible.builtin.debug:
      var: item
    loop: "{{ domain_definition | community.general.json_query('domain.cluster[*].name') }}"    
