---
  - name: VMware VM Inventory Generator
    hosts: localhost
    gather_facts: no
    vars:
      file: file.txt
    tasks:       
      - name: Display all cluster names
        ansible.builtin.debug:
          var: file
        loop: "{{ domain_definition | community.general.json_query('domain.cluster[*].name') }}"    
